### ISSUE TITLE
Are you aware of the typography module

### ISSUE THREAD

**Issue by lf-araujo** [jangko/nimpdf#23]
Thanks for this amazing software. 

Just wanted to call your attention for this typography module, written in Nim. Perhaps it can be incorporated into your work too:

https://github.com/treeform/typography

Keep up.

**Comment by jangko** [comment]
Thank you for the information.
Due to the format/spec of PDF itself, only a subset of `typography` functionality can be used along with nimPDF. And that functionality is the `typesetting`.

* simple way to incorporate typography:
  - calculate the layout using typography
  - draw the layout using nimPDF
  - the result is bigger pdf file.

* hard way to incorporate typography:
  - grab typography layout source code
  - add it into nimPDF text renderer
  - produce smaller pdf file

But I believe I have to go the hard way because of intricate glyph handling required by PDF internal.
I still remember the nightmare of development hell when I implement TTF and unicode support in nimPDF.

**Comment by lf-araujo** [comment]
Thanks for the info!
